# Generated by Django 5.0.14 on 2026-09-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_enable_settings_module'),
        ('employees', '0015_contractversion_signature_image'),
        ('orgchart', '0003_position_company_noconstraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'نوع پروژه',
                'verbose_name_plural': 'انواع پروژه',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('code', models.CharField(max_length=50, verbose_name='کد پروژه')),
                ('name', models.CharField(max_length=250, verbose_name='نام پروژه')),
                ('client', models.CharField(blank=True, max_length=250, verbose_name='کارفرما')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='محل اجرا')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('on_hold', 'متوقف'), ('completed', 'تکمیل\u200cشده'), ('closed', 'بسته')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee', verbose_name='مدیر پروژه')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype', verbose_name='نوع پروژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'دسته منبع',
                'verbose_name_plural': 'دسته\u200cهای منبع',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WBSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_templates', to='projects.projecttype', verbose_name='نوع پروژه')),
            ],
            options={
                'verbose_name': 'قالب WBS',
                'verbose_name_plural': 'قالب\u200cهای WBS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CBSNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('node_type', models.CharField(choices=[('cost_class', 'طبقه هزینه'), ('cost_group', 'گروه هزینه'), ('cost_category', 'دسته هزینه'), ('cost_element', 'عنصر هزینه')], default='cost_category', max_length=30, verbose_name='نوع گره')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.cbsnode', verbose_name='گره بالادستی')),
            ],
            options={
                'verbose_name': 'گره CBS',
                'verbose_name_plural': 'ساختار شکست هزینه (CBS)',
                'ordering': ['sequence', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CostSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'منشأ هزینه',
                'verbose_name_plural': 'منشأهای هزینه',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OBSNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_nodes', to='employees.department', verbose_name='دپارتمان مرجع')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_nodes', to='employees.employee', verbose_name='مسئول مرجع')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.obsnode', verbose_name='گره بالادستی')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_nodes', to='orgchart.position', verbose_name='پوزیشن مرجع')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_nodes', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'گره OBS',
                'verbose_name_plural': 'ساختار شکست سازمانی (OBS)',
                'ordering': ['sequence', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان فاز')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'فاز پروژه',
                'verbose_name_plural': 'فازهای پروژه',
                'ordering': ['sequence', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='projects.resourcecategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WBSNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('node_type', models.CharField(choices=[('project', 'پروژه'), ('phase', 'فاز'), ('deliverable', 'تحویل\u200cدادنی'), ('control_account', 'حساب کنترلی'), ('work_package', 'بسته کاری'), ('activity', 'فعالیت'), ('milestone', 'نقطه عطف')], default='work_package', max_length=30, verbose_name='نوع گره')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.wbsnode', verbose_name='گره بالادستی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_nodes', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'گره WBS',
                'verbose_name_plural': 'ساختار شکست کار (WBS)',
                'ordering': ['sequence', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
    ]
