# Generated by Django 5.0.14 on 2026-09-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_guarantee_instruments'),
        ('core', '0008_enable_projects_module'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام فهرست\u200cبها')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('discipline', models.CharField(blank=True, max_length=100, verbose_name='رشته / دیسیپلین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'فهرست\u200cبها',
                'verbose_name_plural': 'فهرست\u200cبهاها',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PriceListVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('version', models.CharField(max_length=50, verbose_name='نسخه')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.pricelist', verbose_name='فهرست\u200cبها')),
            ],
            options={
                'verbose_name': 'نسخه فهرست\u200cبها',
                'verbose_name_plural': 'نسخه\u200cهای فهرست\u200cبها',
                'ordering': ['price_list', '-year', 'version'],
                'unique_together': {('price_list', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PriceListChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='projects.pricelistversion', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'فصل فهرست\u200cبها',
                'verbose_name_plural': 'فصل\u200cهای فهرست\u200cبها',
                'ordering': ['version', 'code'],
                'unique_together': {('version', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ContractPriceBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('pricing_method', models.CharField(blank=True, max_length=50, verbose_name='روش قیمت\u200cگذاری')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bases', to='contracts.contract', verbose_name='قرارداد')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_bases', to='projects.pricelist', verbose_name='فهرست\u200cبها')),
                ('price_list_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_bases', to='projects.pricelistversion', verbose_name='نسخه فهرست\u200cبها')),
            ],
            options={
                'verbose_name': 'مبنای قیمت قرارداد',
                'verbose_name_plural': 'مبناهای قیمت قرارداد',
                'ordering': ['contract'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='واحد')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='نرخ واحد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'ردیف قرارداد / BOQ',
                'verbose_name_plural': 'ردیف\u200cهای قرارداد / BOQ',
                'ordering': ['contract', 'code'],
                'unique_together': {('contract', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ContractWBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_links', to='contracts.contract', verbose_name='قرارداد')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_links', to='projects.wbsnode', verbose_name='گره WBS')),
            ],
            options={
                'verbose_name': 'نگاشت قرارداد-WBS',
                'verbose_name_plural': 'نگاشت\u200cهای قرارداد-WBS',
                'unique_together': {('contract', 'wbs')},
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='واحد')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='نرخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.pricelistchapter', verbose_name='فصل')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'ردیف فهرست\u200cبها',
                'verbose_name_plural': 'ردیف\u200cهای فهرست\u200cبها',
                'ordering': ['chapter', 'code'],
                'unique_together': {('chapter', 'code')},
            },
        ),
    ]
