# Generated by Django 5.0.14 on 2026-08-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام دپارتمان')),
                ('code', models.CharField(max_length=50, verbose_name='کد دپارتمان')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='employees.department', verbose_name='دپارتمان بالادستی')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InsuranceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام لیست بیمه')),
                ('code', models.CharField(help_text='کد کارگاهی در سازمان تأمین اجتماعی', max_length=50, verbose_name='کد کارگاهی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'لیست بیمه',
                'verbose_name_plural': 'لیست\u200cهای بیمه',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان شغلی')),
                ('code', models.CharField(max_length=50, verbose_name='کد شغل')),
                ('level', models.CharField(choices=[('executive', 'مدیریتی'), ('expert', 'کارشناسی'), ('operational', 'عملیاتی')], default='expert', max_length=20, verbose_name='سطح شغلی')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='employees.jobtitle', verbose_name='عنوان شغلی بالادستی')),
            ],
            options={
                'verbose_name': 'عنوان شغلی',
                'verbose_name_plural': 'عناوین شغلی',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام محل استقرار')),
                ('code', models.CharField(max_length=50, verbose_name='کد محل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'محل استقرار',
                'verbose_name_plural': 'محل\u200cهای استقرار',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل تولد')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'همسر فوت\u200cشده')], max_length=20, verbose_name='وضعیت تأهل')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فرزندان')),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام همسر')),
                ('national_id_serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='سریال شناسنامه')),
                ('national_id_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل صدور شناسنامه')),
                ('national_id_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور شناسنامه')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(max_length=15, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فرد مورد تماس اضطراری')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن اضطراری')),
                ('employee_id', models.CharField(max_length=20, verbose_name='کد پرسنلی')),
                ('hire_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان دوره آزمایشی')),
                ('official_date', models.DateField(blank=True, null=True, verbose_name='تاریخ رسمی شدن')),
                ('contract_type', models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'موقت'), ('project', 'پروژه\u200cای'), ('contractor', 'پیمانی')], max_length=20, verbose_name='نوع قرارداد')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع قرارداد')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان قرارداد')),
                ('status', models.CharField(choices=[('active', 'شاغل'), ('leave', 'مرخصی طولانی\u200cمدت'), ('retired', 'بازنشسته'), ('terminated', 'اخراج'), ('deceased', 'فوت')], default='active', max_length=20, verbose_name='وضعیت')),
                ('status_change_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تغییر وضعیت')),
                ('work_shift', models.CharField(blank=True, choices=[('morning', 'صبح'), ('evening', 'عصر'), ('rotating', 'شیفتی'), ('irregular', 'نامنظم')], max_length=20, null=True, verbose_name='نوبت کاری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='دپارتمان')),
                ('insurance_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.insurancelist', verbose_name='لیست بیمه')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle', verbose_name='عنوان شغلی')),
                ('work_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.worklocation', verbose_name='محل استقرار')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='employees_e_company_806579_idx'), models.Index(fields=['company', 'department'], name='employees_e_company_ba5a2a_idx'), models.Index(fields=['company', 'employee_id'], name='employees_e_company_8aca92_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'national_id'), name='unique_company_national_id'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_id'), name='unique_company_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'mobile'), name='unique_company_mobile'),
        ),
    ]
