# Generated by Django 5.0.14 on 2026-08-16 10:42

import django.db.models.deletion
from django.db import migrations, models


def clear_stale_contract_types(apps, schema_editor):
    """Clear old string values in contract_type before converting to FK."""
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.update(contract_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0003_alter_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام نوع قرارداد')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'نوع قرارداد',
                'verbose_name_plural': 'انواع قرارداد',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.RunPython(clear_stale_contract_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.contracttype', verbose_name='نوع قرارداد'),
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه قرارداد')),
                ('year', models.PositiveIntegerField(verbose_name='سال قرارداد')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='حقوق پایه (ریال)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_versions', to='employees.contracttype', verbose_name='نوع قرارداد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_versions', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'نسخه قرارداد',
                'verbose_name_plural': 'نسخه\u200cهای قرارداد',
                'ordering': ['-year', '-version'],
                'indexes': [models.Index(fields=['company', 'employee', 'year'], name='employees_c_company_cfaaa4_idx')],
                'unique_together': {('company', 'employee', 'year', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EmploymentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('change_type', models.CharField(choices=[('hire', 'استخدام'), ('promotion', 'ارتقا / ترفیع'), ('demotion', 'تنزل مقام'), ('job_title_change', 'تغییر عنوان شغلی'), ('department_change', 'تغییر دپارتمان'), ('location_change', 'تغییر محل کار'), ('salary_increase', 'افزایش حقوق'), ('salary_decrease', 'کاهش حقوق'), ('contract_renewal', 'تمدید قرارداد'), ('contract_termination', 'پایان قرارداد'), ('status_change', 'تغییر وضعیت استخدامی'), ('other', 'سایر')], max_length=30, verbose_name='نوع تغییر')),
                ('effective_date', models.DateField(verbose_name='تاریخ اعمال تغییر')),
                ('year', models.PositiveIntegerField(verbose_name='سال تغییر')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='مقدار قبلی')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='مقدار جدید')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, help_text='برای تغییرات حقوقی', max_digits=15, null=True, verbose_name='مبلغ تغییر (ریال)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_changes', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'تغییر شغلی',
                'verbose_name_plural': 'تغییرات شغلی',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'employee', 'year'], name='employees_e_company_145ae0_idx'), models.Index(fields=['company', 'change_type'], name='employees_e_company_7de381_idx')],
            },
        ),
    ]
