# Generated by Django 5.0.14 on 2026-08-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0004_contracttype_alter_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='distance_to_work_km',
            field=models.PositiveIntegerField(default=0, verbose_name='مسافت خانه تا محل کار (کیلومتر)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_field',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رشته / مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('under_diploma', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, null=True, verbose_name='میزان تحصیلات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='performance_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='۰ تا ۱۰۰ — از ارزیابی\u200cهای دوره\u200cای', max_digits=5, null=True, verbose_name='نمره عملکرد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='satisfaction_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='۰ تا ۱۰۰ — از پرسشنامه\u200cهای ارزیابی', max_digits=5, null=True, verbose_name='نمره رضایت شغلی'),
        ),
        migrations.CreateModel(
            name='EmployeePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ جریمه (ریال)')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل جریمه')),
                ('date', models.DateField(verbose_name='تاریخ جریمه')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'جریمه پرسنلی',
                'verbose_name_plural': 'جرائم پرسنلی',
                'ordering': ['-date'],
            },
        ),
    ]
