# Generated by Django 5.0.14 on 2026-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_end_time',
            field=models.CharField(blank=True, help_text='فرمت ۲۴ ساعته: مثال ۱۶:۰۰', max_length=5, null=True, verbose_name='ساعت پایان کار'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_start_time',
            field=models.CharField(blank=True, help_text='فرمت ۲۴ ساعته: مثال ۰۸:۰۰', max_length=5, null=True, verbose_name='ساعت شروع کار'),
        ),
    ]
