# Generated by Django 5.0.14 on 2026-08-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_work_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_car',
            field=models.BooleanField(default=False, verbose_name='دارای خودروی شخصی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('owned', 'شخصی'), ('mortgage', 'رهن'), ('rental', 'اجاره')], max_length=20, null=True, verbose_name='نوع مسکن'),
        ),
    ]
