# Generated by Django 5.0.14 on 2026-09-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('employees', '0009_employee_has_car_employee_housing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بانک'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل اخذ مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره بیمه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='employee',
            name='university_type',
            field=models.CharField(blank=True, choices=[('state', 'دولتی'), ('azad', 'آزاد'), ('payam_noor', 'پیام نور'), ('nonprofit', 'غیرانتفاعی'), ('technical', 'فنی و حرفه\u200cای'), ('other', 'سایر')], max_length=20, null=True, verbose_name='نوع دانشگاه'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='contractversion',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='employmentchange',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='insurancelist',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.CreateModel(
            name='SupplementaryInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('insurance_name', models.CharField(max_length=200, verbose_name='نام بیمه تکمیلی')),
                ('insurance_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بیمه تکمیلی')),
                ('plan', models.CharField(blank=True, max_length=200, null=True, verbose_name='طرح انتخابی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خاتمه')),
                ('monthly_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ ماهانه (ریال)')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل (ریال)')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_insurances', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'بیمه تکمیلی',
                'verbose_name_plural': 'بیمه\u200cهای تکمیلی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplementaryInsuranceDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('relation', models.CharField(choices=[('spouse', 'همسر'), ('child', 'فرزند'), ('father', 'پدر'), ('mother', 'مادر'), ('other', 'سایر')], max_length=50, verbose_name='نسبت')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.supplementaryinsurance', verbose_name='بیمه تکمیلی')),
            ],
            options={
                'verbose_name': 'فرد تحت تکفل',
                'verbose_name_plural': 'افراد تحت تکفل',
                'ordering': ['id'],
            },
        ),
    ]
