# Generated by Django 5.0.14 on 2026-09-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('employees', '0010_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('request_type', models.CharField(choices=[('transfer', 'انتقال واحد'), ('promotion', 'ارتقا شغلی'), ('resignation', 'استعفا'), ('retirement', 'بازنشستگی'), ('shift_change', 'تغییر شیفت'), ('certificate', 'صدور گواهی اشتغال'), ('salary_increase', 'افزایش حقوق'), ('other', 'سایر')], default='transfer', max_length=30, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('target_value', models.CharField(blank=True, help_text='مثلاً واحد/سمت/شیفت جدید، یا مبلغ برای افزایش حقوق', max_length=200, verbose_name='ارزش هدف')),
                ('description', models.TextField(blank=True, verbose_name='شرح درخواست')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_requests', to='employees.employee', verbose_name='پرسنل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hr_requests', to='employees.employee', verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست اداری',
                'verbose_name_plural': 'درخواست\u200cهای اداری',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='employees_h_company_9126ce_idx'), models.Index(fields=['company', 'request_type'], name='employees_h_company_e34a9a_idx')],
            },
        ),
    ]
