# Generated by Django 5.0.14 on 2026-09-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('contracts', '0009_contract_statement_currency'),
        ('core', '0010_enable_accounting_module'),
        ('employees', '0017_is_record_complete'),
        ('projects', '0003_budgetline_committedcost_costtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliaryaccount',
            name='aux_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='سطح تفصیلی (۱ تا ۳)'),
        ),
        migrations.AddField(
            model_name='auxiliaryaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.auxiliaryaccount', verbose_name='تفصیلی بالادستی'),
        ),
        migrations.AddIndex(
            model_name='auxiliaryaccount',
            index=models.Index(fields=['parent', 'aux_level'], name='accounting__parent__d0c7eb_idx'),
        ),
    ]
