# Generated by Django 5.0.14 on 2026-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auxiliaryaccount_aux_level_auxiliaryaccount_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='nature',
            field=models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار')], default='debit', max_length=10, verbose_name='ماهیت'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='category',
            field=models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'حقوق مالکانه'), ('revenue', 'درآمد'), ('cost_of_sales', 'بهای تمام\u200cشده'), ('expense', 'هزینه'), ('memorandum', 'حساب\u200cهای انتظامی')], max_length=20, verbose_name='طبقه'),
        ),
    ]
