# Generated by Django 5.0.14 on 2026-09-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountgroup_nature_alter_accounttype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'نوع حساب', 'verbose_name_plural': 'انواع حساب'},
        ),
        migrations.AddField(
            model_name='accounttype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='nature',
            field=models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار'), ('none', 'مهم نیست')], default='none', max_length=10, verbose_name='ماهیت'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='default_nature',
            field=models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار'), ('none', 'مهم نیست')], default='none', max_length=10, verbose_name='ماهیت پیش\u200cفرض'),
        ),
    ]
