# Generated by Django 5.0.14 on 2026-09-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_accounttype_options_accounttype_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='code',
            field=models.CharField(max_length=20, verbose_name='کد'),
        ),
    ]
