# Generated by Django 5.0.14 on 2026-09-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_accounttype_code'),
        ('core', '0010_enable_accounting_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('level', models.CharField(choices=[('account_type', 'نوع حساب'), ('group', 'گروه حساب'), ('general', 'حساب کل'), ('subsidiary', 'حساب معین'), ('auxiliary', 'حساب تفصیلی'), ('cost_center', 'مرکز هزینه')], max_length=20, verbose_name='سطح کدینگ')),
                ('prefix', models.CharField(blank=True, max_length=20, verbose_name='پیشوند کد')),
                ('start_number', models.PositiveIntegerField(default=1, verbose_name='شروع از')),
                ('end_number', models.PositiveIntegerField(default=99, verbose_name='پایان تا')),
                ('min_length', models.PositiveSmallIntegerField(default=1, verbose_name='حداقل طول')),
                ('max_length', models.PositiveSmallIntegerField(default=10, verbose_name='حداکثر طول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'پیکربندی کدینگ',
                'verbose_name_plural': 'پیکربندی کدینگ',
                'ordering': ['level'],
                'unique_together': {('company', 'level')},
            },
        ),
    ]
