# Generated by Django 5.0.14 on 2026-09-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_codingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nature',
            field=models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار'), ('none', 'مهم نیست')], default='debit', max_length=10, verbose_name='ماهیت'),
        ),
    ]
