# Generated by Django 5.0.14 on 2026-09-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_account_nature'),
        ('core', '0010_enable_accounting_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=30, verbose_name='کد دسته')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان دسته')),
                ('source', models.CharField(choices=[('manual', 'دستی'), ('employee', 'پرسنل'), ('party', 'طرف حساب'), ('project', 'پروژه'), ('contract', 'قرارداد'), ('bank', 'بانک'), ('cash', 'صندوق')], default='manual', max_length=20, verbose_name='منبع داده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تفصیلی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تفصیلی',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='auxiliary_categories',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='accounting.auxiliarycategory', verbose_name='دسته\u200cبندی\u200cهای تفصیلی مجاز'),
        ),
        migrations.AddField(
            model_name='auxiliaryaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliaries', to='accounting.auxiliarycategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
