# Generated by Django 5.0.14 on 2026-09-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auxiliarycategory_account_auxiliary_categories_and_more'),
        ('contracts', '0009_contract_statement_currency'),
        ('core', '0010_enable_accounting_module'),
        ('employees', '0017_is_record_complete'),
        ('projects', '0003_budgetline_committedcost_costtransaction_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auxiliaryaccount',
            name='accounting__parent__d0c7eb_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='auxiliary_categories',
        ),
        migrations.RemoveField(
            model_name='auxiliaryaccount',
            name='aux_level',
        ),
        migrations.AddField(
            model_name='account',
            name='auxiliary_category_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_cat1', to='accounting.auxiliarycategory', verbose_name='ارتباط با تفصیل یک'),
        ),
        migrations.AddField(
            model_name='account',
            name='auxiliary_category_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_cat2', to='accounting.auxiliarycategory', verbose_name='ارتباط با تفصیل دو'),
        ),
        migrations.AddField(
            model_name='account',
            name='auxiliary_category_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_cat3', to='accounting.auxiliarycategory', verbose_name='ارتباط با تفصیل سه'),
        ),
        migrations.AlterField(
            model_name='auxiliaryaccount',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliaries', to='accounting.account', verbose_name='حساب مرتبط'),
        ),
        migrations.AddIndex(
            model_name='auxiliaryaccount',
            index=models.Index(fields=['parent'], name='accounting__parent__22751a_idx'),
        ),
    ]
