# Generated by Django 5.0.14 on 2026-09-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_auxiliaryaccount_accounting__parent__d0c7eb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocumentline',
            name='auxiliary_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_1', to='accounting.auxiliaryaccount', verbose_name='تفصیل یک'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='auxiliary_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_2', to='accounting.auxiliaryaccount', verbose_name='تفصیل دو'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='auxiliary_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_3', to='accounting.auxiliaryaccount', verbose_name='تفصیل سه'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ (سررسید)'),
        ),
    ]
