# Generated by Django 5.0.14 on 2026-09-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingdocumentline_auxiliary_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdocument',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.fiscalyear', verbose_name='سال مالی'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.journal', verbose_name='دفتر روزنامه'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.fiscalperiod', verbose_name='دوره'),
        ),
    ]
