# Generated by Django 5.0.14 on 2026-09-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_accountingdocument_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingtemplate',
            name='description_template',
            field=models.JSONField(blank=True, default=list, verbose_name='الگوی شرح سند'),
        ),
    ]
