# Generated by Django 5.0.14 on 2026-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_postingtemplate_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='history',
            field=models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه'),
        ),
    ]
