# Generated by Django 5.0.14 on 2026-09-23 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_accountingdocument_history'),
        ('core', '0010_enable_accounting_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('as_of', models.DateField(verbose_name='تاریخ مغایرت\u200cگیری')),
                ('statement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ماندهٔ نظام بانکی')),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ماندهٔ دفتری')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='اختلاف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.account', verbose_name='حساب بانکی/صندوق')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'مغایرت\u200cگیری بانکی',
                'verbose_name_plural': 'مغایرت\u200cگیری\u200cهای بانکی',
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('statement_date', models.DateField(verbose_name='تاریخ صورتحساب')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره صورتحساب')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ماندهٔ ابتدای دوره')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ماندهٔ انتهای دوره')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='accounting.account', verbose_name='حساب بانکی/صندوق')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'صورتحساب بانکی',
                'verbose_name_plural': 'صورتحساب\u200cهای بانکی',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='شرح')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ')),
                ('currency', models.CharField(choices=[('debit', 'برداشت'), ('credit', 'واریز')], default='debit', max_length=10, verbose_name='جهت')),
                ('matched', models.BooleanField(default=False, verbose_name='تطبیق\u200cشده')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement', verbose_name='صورتحساب')),
            ],
            options={
                'verbose_name': 'ردیف صورتحساب بانکی',
                'verbose_name_plural': 'ردیف\u200cهای صورتحساب بانکی',
                'ordering': ['date'],
            },
        ),
    ]
