# Generated by Django 5.0.14 on 2026-09-23 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_bankreconciliation_bankstatement_bankstatementline'),
        ('core', '0010_enable_accounting_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان سیاست')),
                ('single_level_limit', models.DecimalField(decimal_places=0, default=50000000, max_digits=18, verbose_name='سقف تأیید تک\u200cمرحله (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'سیاست تأیید اسناد',
                'verbose_name_plural': 'سیاست\u200cهای تأیید اسناد',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('step_no', models.PositiveIntegerField(default=1, verbose_name='مرحله')),
                ('decision', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید'), ('rejected', 'رد')], default='pending', max_length=10, verbose_name='تصمیم')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='accounting.accountingdocument', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'مرحلهٔ تأیید سند',
                'verbose_name_plural': 'مراحل تأیید اسناد',
                'ordering': ['step_no'],
            },
        ),
    ]
