# Generated by Django 5.0.14 on 2026-09-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_approvalpolicy_approvalstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocumentline',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='invoice_type',
            field=models.CharField(choices=[('sale', 'فروش کالا / خدمات'), ('purchase', 'خرید کالا / خدمات'), ('import', 'واردات'), ('export', 'صادرات'), ('service', 'قرارداد خدمت'), ('none', 'نامشخص')], default='none', max_length=20, verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='party_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='شناسه ملی / کد ملی طرف'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='party_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی طرف'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='party_tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره اقتصادی طرف معامله'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='season_flag',
            field=models.BooleanField(default=False, verbose_name='مشمول معاملات فصلی'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ ارزش افزوده (٪)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='retained_earnings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='حساب سود/زیان انباشته'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='profit_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='حساب خلاصه سود و زیان'),
        ),
    ]
