# Generated by Django 5.0.14 on 2026-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_accountingdocumentline_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره عطف'),
        ),
    ]
