# Generated by Django 5.0.14 on 2026-09-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingdocument_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdocument',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='شناسهٔ منبع'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='source_module',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ماژول منبع'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='نوع منبع'),
        ),
    ]
