# Generated by Django 5.0.14 on 2026-09-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_accountingdocument_source_id_and_more'),
        ('procurement', '0001_initial'),
        ('treasury', '0005_treasuryreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliaryaccount',
            name='person_type',
            field=models.CharField(blank=True, choices=[('legal', 'شخص حقوقی'), ('natural', 'شخص حقیقی')], max_length=10, null=True, verbose_name='نوع شخص'),
        ),
        migrations.AddField(
            model_name='auxiliaryaccount',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliary_accounts', to='procurement.supplier', verbose_name='تأمین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='auxiliaryaccount',
            name='treasury_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliary_accounts', to='treasury.treasuryentity', verbose_name='بانک/صندوق'),
        ),
    ]
