# Generated by Django 5.0.14 on 2026-08-11 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(default='public', max_length=63, unique=True)),
                ('domain_url', models.CharField(blank=True, max_length=128, null=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('name', models.CharField(help_text='نام کامل شرکت', max_length=200, verbose_name='نام شرکت')),
                ('code', models.CharField(help_text='کد یکتای شرکت', max_length=50, unique=True, verbose_name='کد شرکت')),
                ('email', models.EmailField(blank=True, help_text='آدرس ایمیل شرکت', max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, help_text='شماره تماس شرکت', max_length=20, null=True, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, help_text='آدرس پستی شرکت', null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, help_text='کد پستی شرکت', max_length=20, null=True, verbose_name='کد پستی')),
                ('national_id', models.CharField(blank=True, help_text='شماره شناسه ملی شرکت', max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, help_text='کد اقتصادی شرکت', max_length=20, null=True, verbose_name='کد اقتصادی')),
                ('registration_number', models.CharField(blank=True, help_text='شماره ثبت شرکت', max_length=50, null=True, verbose_name='شماره ثبت')),
                ('logo', models.ImageField(blank=True, help_text='لوگوی شرکت', null=True, upload_to='company_logos/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن شرکت', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('is_primary', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.company')),
            ],
            options={
                'verbose_name': 'دامنه',
                'verbose_name_plural': 'دامنه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'مدیر ارشد سیستم'), ('hr_manager', 'مدیر منابع انسانی'), ('hr_specialist', 'کارشناس منابع انسانی'), ('department_head', 'مدیر دپارتمان'), ('employee', 'کارمند')], default='employee', max_length=30, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('companies', models.ManyToManyField(blank=True, related_name='users', to='core.company', verbose_name='شرکت\u200cهای قابل دسترس')),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.company', verbose_name='شرکت جاری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'به\u200cروزرسانی'), ('DELETE', 'حذف'), ('LOGIN', 'ورود'), ('LOGOUT', 'خروج'), ('VIEW', 'مشاهده'), ('EXPORT', 'خروجی'), ('APPROVE', 'تأیید'), ('REJECT', 'رد')], max_length=20, verbose_name='عملیات')),
                ('model_name', models.CharField(help_text='نام مدل مورد نظر (مثلاً Employee, Leave)', max_length=100, verbose_name='نام مدل')),
                ('object_id', models.CharField(blank=True, help_text='شناسه رکورد مورد نظر', max_length=100, null=True, verbose_name='شناسه شیء')),
                ('changes', models.JSONField(blank=True, help_text='داده\u200cهای تغییر یافته (فرمت JSON)', null=True, verbose_name='تغییرات')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی در مورد عملیات', null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'لاگ عملیات',
                'verbose_name_plural': 'لاگ\u200cهای عملیات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'action'], name='core_auditl_company_e2184a_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx')],
            },
        ),
    ]
