# Generated by Django 5.0.14 on 2026-09-03 10:05

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, unique=True, verbose_name='نقش')),
                ('permissions', models.JSONField(default=dict, verbose_name='دسترسی\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسترسی نقش',
                'verbose_name_plural': 'دسترسی\u200cهای نقش',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='company',
            name='domain_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='company',
            name='paid_until',
        ),
        migrations.AlterField(
            model_name='company',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
