# Generated by Django 5.0.14 on 2026-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_enable_treasury_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='applications',
            field=models.JSONField(blank=True, default=list, help_text='لیست شناسه (slug) سامانه\u200cهایی که این نقش به آن\u200cها دسترسی دارد. خالی یعنی استفاده از پیش\u200cفرض نقش.', verbose_name='سامانه\u200cهای مجاز'),
        ),
    ]
