# Generated by Django 5.0.14 on 2026-08-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پوزیشن')),
                ('code', models.CharField(max_length=50, verbose_name='کد پوزیشن')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='سطح در درخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='employees.department', verbose_name='دپارتمان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orgchart.position', verbose_name='پوزیشن بالادستی')),
            ],
            options={
                'verbose_name': 'پوزیشن سازمانی',
                'verbose_name_plural': 'پوزیشن\u200cهای سازمانی',
                'ordering': ['level', 'title'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
