# Generated by Django 5.0.14 on 2026-08-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('orgchart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='positions', to='employees.employee', verbose_name='پرسنل مستقر در جایگاه'),
        ),
    ]
