import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_userprofile_employee_id'),
        ('settings_app', '0009_alter_companyprofile_storage_path_correspondences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=250, verbose_name='نام / عنوان')),
                ('party_type', models.CharField(choices=[('contractor', 'پیمانکار'), ('supplier', 'فروشنده / تأمین‌کننده'), ('consultant', 'مشاور'), ('other', 'سایر')], default='contractor', max_length=20, verbose_name='نوع طرف')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='شناسه ملی / کد ثبت')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='شماره ثبت')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='شخص رابط')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('sheba_number', models.CharField(blank=True, max_length=30, verbose_name='شماره شبا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'طرف قرارداد',
                'verbose_name_plural': 'طرف‌های قرارداد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='شماره قرارداد')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع قرارداد')),
                ('contract_type', models.CharField(choices=[('construction', 'پیمانکاری / اجرا'), ('purchase', 'خرید'), ('tender', 'مناقصه'), ('consulting', 'مشاوره'), ('service', 'خدمات'), ('other', 'سایر')], default='purchase', max_length=20, verbose_name='نوع قرارداد')),
                ('status', models.CharField(choices=[('draft', 'پیش‌نویس'), ('active', 'در حال اجرا'), ('suspended', 'متوقف'), ('completed', 'تکمیل شده'), ('terminated', 'فسخ شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='مبلغ قرارداد (ریال)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('guarantee_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='مبلغ تضمین (ریال)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contractparty', verbose_name='طرف قرارداد')),
                ('signatory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_contracts', to='settings_app.signatory', verbose_name='امضاکنندهٔ مجاز')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سند')),
                ('file', models.FileField(upload_to='contract_documents/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'سند قرارداد',
                'verbose_name_plural': 'اسناد قرارداد',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='شماره فاکتور')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ فاکتور')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ (ریال)')),
                ('vat', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مالیات (ریال)')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل (ریال)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='شماره صورت‌وضعیت')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ (ریال)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'صورت‌وضعیت',
                'verbose_name_plural': 'صورت‌وضعیت‌ها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='شماره الحاقیه')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('change_description', models.TextField(blank=True, verbose_name='شرح تغییرات')),
                ('amount_change', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='تغییر مبلغ (ریال)')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان جدید')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'الحاقیه',
                'verbose_name_plural': 'الحاقیه‌ها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('guarantee_type', models.CharField(choices=[('performance', 'ضمانت حسن انجام کار'), ('advance', 'ضمانت پیش‌پرداخت'), ('bid', 'ضمانت شرکت در مناقصه'), ('other', 'سایر')], default='performance', max_length=20, verbose_name='نوع تضمین')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='شماره')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ (ریال)')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='بانک صادرکننده')),
                ('is_released', models.BooleanField(default=False, verbose_name='آزاد شده')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'تضمین',
                'verbose_name_plural': 'تضمین‌ها',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ (ریال)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع / سند')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='روش پرداخت')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='قرارداد')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.invoice', verbose_name='فاکتور مرتبط')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت‌ها',
                'ordering': ['-date'],
            },
        ),
    ]