# Generated by Django 5.0.14 on 2026-09-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_guarantee_instruments'),
        ('projects', '0003_budgetline_committedcost_costtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_contracts', to='projects.project', verbose_name='پروژه'),
        ),
    ]
