# Generated by Django 5.0.14 on 2026-09-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_project'),
        ('core', '0008_enable_projects_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('title', models.CharField(max_length=250, verbose_name='موضوع اختلاف')),
                ('dispute_type', models.CharField(choices=[('financial', 'مالی'), ('technical', 'فنی'), ('timeline', 'زمان\u200cبندی / تأخیر'), ('quality', 'کیفیت'), ('legal', 'حقوقی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع اختلاف')),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='شدت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('under_review', 'در حال بررسی'), ('resolved', 'حل\u200cشده'), ('escalated', 'ارجاع به مرجع بالاتر'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='مبلغ ادعا (ریال)')),
                ('opened_date', models.DateField(blank=True, null=True, verbose_name='تاریخ طرح')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='تاریخ حل')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('resolution', models.TextField(blank=True, verbose_name='اقدام/نتیجه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'اختلاف قرارداد',
                'verbose_name_plural': 'اختلافات و دعاوی',
                'ordering': ['-opened_date', '-created_at'],
            },
        ),
    ]
