# Generated by Django 5.0.14 on 2026-09-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractdispute'),
        ('core', '0008_enable_projects_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('evaluation_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ارزیابی')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='دوره ارزیابی')),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='کیفیت (۰-۱۰۰)')),
                ('delivery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تحویل به\u200cموقع (۰-۱۰۰)')),
                ('price_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='قیمت (۰-۱۰۰)')),
                ('cooperation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='همکاری (۰-۱۰۰)')),
                ('safety_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ایمنی/HSE (۰-۱۰۰)')),
                ('recommendation', models.CharField(choices=[('approved', 'تأییدشده'), ('conditional', 'تأیید مشروط'), ('suspended', 'تعلیق'), ('blacklisted', 'لیست سیاه')], default='approved', max_length=20, verbose_name='نتیجه ارزیابی')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط قوت')),
                ('weaknesses', models.TextField(blank=True, verbose_name='نقاط ضعف')),
                ('evaluator', models.CharField(blank=True, max_length=200, verbose_name='ارزیاب')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='contracts.contract', verbose_name='قرارداد مرتبط')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='contracts.contractparty', verbose_name='طرف قرارداد')),
            ],
            options={
                'verbose_name': 'ارزیابی تأمین\u200cکننده',
                'verbose_name_plural': 'ارزیابی\u200cهای تأمین\u200cکننده',
                'ordering': ['-evaluation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'نوع قرارداد',
                'verbose_name_plural': 'انواع قرارداد',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
