# Generated by Django 5.0.14 on 2026-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_statement_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='person_type',
            field=models.CharField(choices=[('legal', 'شخص حقوقی'), ('natural', 'شخص حقیقی')], default='legal', max_length=10, verbose_name='نوع شخص'),
        ),
    ]
