# Generated by Django 5.0.14 on 2026-10-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contractparty_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='advance_payments',
            field=models.JSONField(blank=True, default=list, help_text='لیست مراحل پیش\u200cپرداخت: [{step, amount, due_date, note}]', verbose_name='پیش\u200cپرداخت\u200cهای مرحله\u200cای'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttypemaster', verbose_name='نوع قرارداد (پیکربندی)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='guarantee_type',
            field=models.CharField(blank=True, choices=[('performance', 'ضمانت حسن انجام کار'), ('advance', 'ضمانت پیش\u200cپرداخت'), ('bid', 'ضمانت شرکت در مناقصه'), ('other', 'سایر')], max_length=20, null=True, verbose_name='نوع ضمانت'),
        ),
    ]
