# Generated by Django 5.0.14 on 2026-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contract_advance_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدیر عامل'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='ceo_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس مدیر عامل'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='company_type',
            field=models.CharField(blank=True, choices=[('public_joint_stock', 'سهامی عام'), ('private_joint_stock', 'سهامی خاص'), ('llc', 'با مسئولیت محدود'), ('cooperative', 'تعاونی'), ('sole_proprietorship', 'مؤسسه انفرادی'), ('branch', 'شعبه / نمایندگی'), ('other', 'سایر')], max_length=30, verbose_name='نوع شرکت'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='finance_manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدیر مالی'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='finance_manager_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس مدیر مالی'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='registered_capital',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='سرمایه ثبتی (ریال)'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='technical_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='رابط فنی و مهندسی'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='technical_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس رابط فنی'),
        ),
    ]
