# Generated by Django 5.0.14 on 2026-10-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contractparty_ceo_name_contractparty_ceo_phone_and_more'),
        ('core', '0013_rolepermission_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان پیش\u200cنویس')),
                ('content', models.TextField(blank=True, verbose_name='متن پیش\u200cنویس')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_approval', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('submitted_by', models.CharField(blank=True, max_length=200, verbose_name='ثبت\u200cکننده')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال برای تأیید')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='contracts.contract', verbose_name='قرارداد مرتبط')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس قرارداد',
                'verbose_name_plural': 'پیش\u200cنویس\u200cها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('step', models.PositiveSmallIntegerField(default=1, verbose_name='مرحله')),
                ('approver', models.CharField(max_length=200, verbose_name='تأییدکننده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شد'), ('rejected', 'رد شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اقدام')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.contractdraft', verbose_name='پیش\u200cنویس')),
            ],
            options={
                'verbose_name': 'مرحله تأیید قرارداد',
                'verbose_name_plural': 'گردش\u200cکار تأیید',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان قالب')),
                ('content', models.TextField(verbose_name='متن / ساختار قالب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract_type_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='contracts.contracttypemaster', verbose_name='نوع قرارداد')),
            ],
            options={
                'verbose_name': 'قالب قرارداد',
                'verbose_name_plural': 'قالب\u200cها و پیش\u200cنویس\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contractdraft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='contracts.contracttemplate', verbose_name='قالب مبدأ'),
        ),
    ]
