# Generated by Django 5.0.14 on 2026-10-04 (manual)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_contractdraft_contractapproval_contracttemplate_and_more'),
        ('core', '0013_rolepermission_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان گردش\u200cکار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='contracts.contracttypemaster', verbose_name='نوع قرارداد')),
            ],
            options={
                'verbose_name': 'گردش\u200cکار تأیید',
                'verbose_name_plural': 'گردش\u200cکارهای تأیید',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('step', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مرحله')),
                ('approver_role', models.CharField(max_length=200, verbose_name='نقش / سمت تأییدکننده')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='آستانه مبلغ (ریال)')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contracts.contractapprovalworkflow', verbose_name='گردش\u200cکار')),
            ],
            options={
                'verbose_name': 'مرحله گردش\u200cکار تأیید',
                'verbose_name_plural': 'مراحل گردش\u200cکار تأیید',
                'ordering': ['workflow', 'step'],
                'unique_together': {('workflow', 'step')},
            },
        ),
    ]
