# Generated by Django 5.0.14 on 2026-10-04 (manual)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contractapprovalworkflow_contractapprovalstep'),
        ('core', '0013_rolepermission_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('user', models.CharField(blank=True, max_length=200, verbose_name='کاربر')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('status', 'تغییر وضعیت')], max_length=20, verbose_name='اقدام')),
                ('field', models.CharField(blank=True, max_length=100, verbose_name='فیلد')),
                ('old_value', models.TextField(blank=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, verbose_name='مقدار جدید')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'سابقه تغییرات قرارداد',
                'verbose_name_plural': 'سوابق تغییرات قرارداد',
                'ordering': ['-created_at'],
            },
        ),
    ]
