# Generated by Django 5.0.14 on 2026-10-04 (manual)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_contractauditlog'),
        ('settings_app', '0011_currency_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='موضوع الحاقیه'),
        ),
        migrations.AddField(
            model_name='addendum',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addendums', to='settings_app.currency', verbose_name='واحد ارز'),
        ),
        migrations.AddField(
            model_name='addendum',
            name='percent_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='درصد تغییر'),
        ),
        migrations.AddField(
            model_name='addendum',
            name='provisions',
            field=models.JSONField(blank=True, default=list, verbose_name='مفاد / بندها'),
        ),
        migrations.AlterField(
            model_name='addendum',
            name='amount_change',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='تغییر مبلغ'),
        ),
    ]
