# Generated by Django 5.0.14 on 2026-10-04 (manual)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_addendum_subject_currency_provisions'),
        ('settings_app', '0011_currency_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='شرح فاکتور'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='settings_app.currency', verbose_name='واحد ارز'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='settings_app.currency', verbose_name='واحد ارز'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ'),
        ),
    ]
