# Generated by Django 5.0.14 on 2026-10-04 (manual)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_invoice_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.statement', verbose_name='صورت\u200cوضعیت مرتبط'),
        ),
    ]
