# Generated by Django 5.0.14 on 2026-10-04 (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_payment_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='نرخ ارز (به ریال)'),
        ),
    ]
