# Generated by Django 5.0.14 (manual) — multi-project allocation + multi-guarantee items

from django.db import migrations, models


GUARANTEE_CHOICES = [
    ('performance', 'ضمانت حسن انجام کار'),
    ('advance', 'ضمانت پیش‌پرداخت'),
    ('bid', 'ضمانت شرکت در مناقصه'),
    ('execution', 'ضمانت اجرای تعهدات'),
    ('insurance', 'سپرده حق بیمه'),
    ('other', 'سایر'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_statement_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='guarantee_items',
            field=models.JSONField(blank=True, default=list, help_text='لیست ضمانت‌ها: [{type, amount, percent, note}]', verbose_name='ضمانت‌ها'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project_allocations',
            field=models.JSONField(blank=True, default=list, help_text='لیست پروژه‌ها با درصد: [{project, percentage}]', verbose_name='تخصیص پروژه‌ها'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guarantee_type',
            field=models.CharField(blank=True, choices=GUARANTEE_CHOICES, max_length=20, null=True, verbose_name='نوع ضمانت'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee_type',
            field=models.CharField(choices=GUARANTEE_CHOICES, default='performance', max_length=20, verbose_name='نوع تضمین'),
        ),
    ]
