# Generated by Django 5.0.14 on 2026-09-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان سند')),
                ('category', models.CharField(choices=[('contract', 'قرارداد سازمانی'), ('agreement', 'تفاهم\u200cنامه'), ('official', 'ابلاغیه/بخشنامه رسمی'), ('license', 'مجوز/پروانه'), ('audit', 'گزارش حسابرسی/مالی'), ('insurance', 'بیمه نامه'), ('certificate', 'گواهی/گواهینامه'), ('hr_doc', 'مستندات منابع انسانی'), ('legal', 'اسناد حقوقی'), ('other', 'سایر')], default='contract', max_length=30, verbose_name='دسته\u200cبندی')),
                ('reference_number', models.CharField(blank=True, max_length=80, verbose_name='شماره ثبت/مرجع')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('file', models.FileField(upload_to='company_archive/%Y/%m/', verbose_name='فایل')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='برچسب\u200cها')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'سند سازمانی',
                'verbose_name_plural': 'اسناد سازمانی (بایگانی)',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'category'], name='documents_o_company_b6c955_idx'), models.Index(fields=['expiry_date'], name='documents_o_expiry__e608c7_idx')],
            },
        ),
    ]
