# Generated by Django 5.0.14 on 2026-09-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('documents', '0002_alter_document_company_alter_documenttype_company_and_more'),
        ('employees', '0010_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocument',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_archive_documents', to='employees.employee', verbose_name='پرسنل مرتبط (اختیاری)'),
        ),
        migrations.AddIndex(
            model_name='organizationdocument',
            index=models.Index(fields=['company', 'employee'], name='documents_o_company_19ca51_idx'),
        ),
    ]
