# Generated by Django 5.0.14 on 2026-09-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_employee_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='company_archive/%Y/%m/', verbose_name='فایل'),
        ),
    ]
