# Generated by Django 5.0.14 on 2026-08-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('transaction_type', models.CharField(choices=[('leave', 'مرخصی'), ('absence', 'غیبت'), ('benefit', 'مزایای رفاهی'), ('salary', 'حقوق پرداختی'), ('deduction', 'کسورات')], max_length=20, verbose_name='نوع تراکنش')),
                ('title', models.CharField(blank=True, help_text='مثال: مرخصی استحقاقی، عیدی، وام، مالیات', max_length=200, verbose_name='عنوان')),
                ('amount', models.DecimalField(decimal_places=0, default=0, help_text='برای حقوق، مزایا، کسورات', max_digits=15, verbose_name='مبلغ (ریال)')),
                ('quantity', models.DecimalField(decimal_places=1, default=0, help_text='روز برای مرخصی/غیبت، تعداد برای مزایا', max_digits=8, verbose_name='مقدار')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'تراکنش پرسنلی',
                'verbose_name_plural': 'تراکنش\u200cهای پرسنلی',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'employee', 'transaction_type'], name='payroll_emp_company_8c89d2_idx'), models.Index(fields=['company', 'transaction_type'], name='payroll_emp_company_8d128d_idx'), models.Index(fields=['company', 'date'], name='payroll_emp_company_6c0299_idx')],
            },
        ),
    ]
