# Generated by Django 5.0.14 on 2026-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransaction',
            name='end_date',
            field=models.DateField(blank=True, help_text='برای مرخصی/غیبت چندروزه', null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='period',
            field=models.CharField(blank=True, help_text='مثلاً: ۱۴۰۴/۰۶ برای حقوق ماهانه', max_length=20, verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره مرجع / فیش'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='start_date',
            field=models.DateField(blank=True, help_text='برای مرخصی/غیبت چندروزه', null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='sub_type',
            field=models.CharField(blank=True, help_text='مثلاً: مرخصی استحقاقی، استعلاجی، عیدی، مالیات', max_length=50, verbose_name='زیرنوع'),
        ),
        migrations.AlterField(
            model_name='employeetransaction',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان اختیاری تراکنش', max_length=200, verbose_name='عنوان'),
        ),
    ]
