# Generated by Django 5.0.14 on 2026-08-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('payroll', '0002_employeetransaction_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=2, verbose_name='ماه')),
                ('work_days', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='کارکرد (روز)')),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='ساعت اضافه\u200cکار')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حقوق پایه')),
                ('overtime_pay', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='اضافه\u200cکاری')),
                ('night_shift', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='شب\u200cکاری')),
                ('shift_work', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='نوبت\u200cکاری')),
                ('attraction_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق جذب')),
                ('supervision_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق سرپرستی')),
                ('workshop_mission', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='ماموریت کارگاهی')),
                ('seniority_base', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='پایه سنوات')),
                ('job_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='فوق\u200cالعاده شغل')),
                ('hardship_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سختی کار')),
                ('travel_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه سفر')),
                ('housing_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق مسکن')),
                ('marriage_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق تأهل')),
                ('children_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق اولاد')),
                ('meal_voucher', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بن کارکنان')),
                ('deferred_salary_1', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حقوق معوقه ۱')),
                ('deferred_salary_2', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حقوق معوقه ۲')),
                ('bonus_reserve', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='عیدی و ذخیره')),
                ('other_benefits', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سایر مزایا')),
                ('mission_days', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='روز مأموریت')),
                ('mission_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق مأموریت')),
                ('total_benefits', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع حقوق و مزایا')),
                ('insurance_subject', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مشمول بیمه')),
                ('employer_insurance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق بیمه سهم کارفرما')),
                ('employee_insurance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق بیمه سهم پرسنل')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مالیات')),
                ('advance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مساعده')),
                ('supplementary_insurance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بیمه تکمیلی')),
                ('employee_loan', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='وام کارکنان')),
                ('work_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کسر کار')),
                ('total_deductions', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع کسور')),
                ('net_payable', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قابل پرداخت')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'فیش حقوقی',
                'verbose_name_plural': 'فیش\u200cهای حقوقی',
                'ordering': ['-year', '-month', 'employee__employee_id'],
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='payroll_sal_company_10e68b_idx'), models.Index(fields=['company', 'employee'], name='payroll_sal_company_f8014f_idx')],
                'unique_together': {('company', 'employee', 'year', 'month')},
            },
        ),
    ]
