# Generated by Django 5.0.14 on 2026-08-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('payroll', '0003_salaryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('month', models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=2, verbose_name='ماه')),
                ('benefit_type', models.CharField(choices=[('performance', 'کارانه'), ('eid_fitr', 'عید سعید فطر'), ('eid_adha', 'عید سعید قربان'), ('eid_ghadir', 'عید سعید غدیر خم'), ('imam_reza_birthday', 'تولد امام رضا (ع)'), ('sports_allowance', 'کمک هزینه ورزش'), ('yalda_night', 'شب یلدا'), ('bahman_22', '۲۲ بهمن'), ('eid_mabath', 'عید مبعث'), ('nowruz_basket', 'سبد نوروزی'), ('fatima_birthday', 'تولد حضرت زهرا (س) و روز زن'), ('ali_birthday', 'تولد حضرت علی (ع) و روز مرد'), ('allowance', 'کمک هزینه'), ('birthday', 'زادروز'), ('ramadan_basket', 'سبد ماه مبارک رمضان')], max_length=30, verbose_name='نوع مزایای رفاهی')),
                ('gross_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ ناخالص')),
                ('reserved_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مالیات ذخیره شده')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ پرداخت شده')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_records', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'مزایا',
                'verbose_name_plural': 'مزایا',
                'ordering': ['-year', '-month', 'employee__employee_id'],
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='payroll_ben_company_34ff99_idx'), models.Index(fields=['company', 'employee'], name='payroll_ben_company_61d333_idx'), models.Index(fields=['company', 'benefit_type'], name='payroll_ben_company_42dc0e_idx')],
                'unique_together': {('company', 'employee', 'year', 'month', 'benefit_type')},
            },
        ),
    ]
