# Generated by Django 5.0.14 on 2026-09-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('employees', '0010_employee_account_number_employee_bank_name_and_more'),
        ('payroll', '0004_benefitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitrecord',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='employeetransaction',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('loan_type', models.CharField(choices=[('qarz', 'وام قرض\u200cالحسنه'), ('car', 'وام خودرو'), ('housing', 'وام مسکن'), ('urgent', 'وام ضروری'), ('other', 'سایر')], default='qarz', max_length=30, verbose_name='نوع وام')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل وام')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='تعداد اقساط')),
                ('installment_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ هر قسط')),
                ('grant_date', models.DateField(verbose_name='تاریخ اعطای وام')),
                ('due_date', models.DateField(blank=True, help_text='اختیاری — تاریخ نهایی تسویه', null=True, verbose_name='تاریخ سررسید/تسویه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('paid', 'تسویه\u200cشده'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='شرح / کاربری')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'وام و تسهیلات',
                'verbose_name_plural': 'وام\u200cها و تسهیلات',
                'ordering': ['-grant_date'],
            },
        ),
    ]
