# Generated by Django 5.0.14 on 2026-09-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_accountingdocument_fiscal_year_and_more'),
        ('core', '0010_enable_accounting_module'),
        ('employees', '0017_is_record_complete'),
        ('pettycash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashExpenseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره صورت')),
                ('date', models.DateField(verbose_name='تاریخ صورت')),
                ('description', models.TextField(blank=True, verbose_name='شرح صورت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال به حسابداری'), ('approved', 'تأیید حسابداری'), ('posted', 'ثبت در سند و تنخواه'), ('rejected', 'برگشت خورده'), ('edited', 'ویرایش\u200cشده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_statements', to='employees.employee', verbose_name='تنخواه\u200cدار')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_statements', to='pettycash.pettycashfund', verbose_name='تنخواه')),
                ('source_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_statement', to='accounting.sourcetransaction', verbose_name='تراکنش منبع حسابداری')),
            ],
            options={
                'verbose_name': 'صورت ریز هزینهٔ تنخواه',
                'verbose_name_plural': 'صورت هزینه\u200cهای تنخواه',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashExpenseStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('line_no', models.PositiveIntegerField(default=0, verbose_name='ردیف')),
                ('description', models.TextField(blank=True, verbose_name='شرح آرتیکل')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ هزینه (ریال)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_statement_lines', to='accounting.account', verbose_name='کد معین')),
                ('auxiliary_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیل یک')),
                ('auxiliary_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیل دو')),
                ('auxiliary_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیل سه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pettycash.pettycashexpensestatement', verbose_name='صورت هزینه')),
            ],
            options={
                'verbose_name': 'سطر صورت هزینهٔ تنخواه',
                'verbose_name_plural': 'سطرهای صورت هزینهٔ تنخواه',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pettycashexpensestatement',
            index=models.Index(fields=['company', 'fund'], name='pettycash_p_company_f5203e_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashexpensestatement',
            index=models.Index(fields=['company', 'status'], name='pettycash_p_company_c81210_idx'),
        ),
    ]
