# Generated by Django 5.0.14 on 2026-09-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0002_pettycashexpensestatement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashexpensestatementline',
            name='expense_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ هزینه'),
        ),
        migrations.AddField(
            model_name='pettycashexpensestatementline',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور'),
        ),
        migrations.AddField(
            model_name='pettycashexpensestatementline',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='فروشنده'),
        ),
        migrations.AlterField(
            model_name='pettycashexpensestatementline',
            name='debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ (ریال)'),
        ),
        migrations.AlterField(
            model_name='pettycashexpensestatementline',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح هزینه'),
        ),
    ]
