# Generated by Django 5.0.14 on 2026-09-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_postingtemplate_description_template'),
        ('pettycash', '0003_pettycashexpensestatementline_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='account',
            field=models.ForeignKey(blank=True, help_text='حساب معینی که هنگام ثبت سند، طرف بستانکار تنخواه قرار می\u200cگیرد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_funds', to='accounting.account', verbose_name='حساب تنخواه (بستانکار)'),
        ),
    ]
