# Generated by Django 5.0.14 on 2026-09-21 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_postingtemplate_description_template'),
        ('pettycash', '0004_pettycashfund_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='auxiliary_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیل یک'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='auxiliary_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیل دو'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='auxiliary_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیل سه'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='general_account',
            field=models.ForeignKey(blank=True, help_text='حساب کل (سطح ۱) که تنخواه به آن متصل است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_funds_general', to='accounting.account', verbose_name='حساب کل'),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='account',
            field=models.ForeignKey(blank=True, help_text='حساب معینی که هنگام ثبت سند، طرف بستانکار تنخواه قرار می\u200cگیرد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_funds', to='accounting.account', verbose_name='حساب معین'),
        ),
    ]
