# Generated by Django 5.0.14 on 2026-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0006_pettycashcategory_budget_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashexpensestatement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف'),
        ),
        migrations.AddField(
            model_name='pettycashexpensestatement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف نرم'),
        ),
    ]
