# Generated by Django 5.0.14 on 2026-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_balesendlog_baleschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('leave_request', 'درخواست مرخصی'), ('hr_request', 'درخواست اداری'), ('contract_expiry', 'انقضای قرارداد'), ('document_expiry', 'انقضای مدرک'), ('leave_balance', 'پایان مانده مرخصی'), ('petty_cash', 'تنخواه')], max_length=30, verbose_name='دسته\u200cبندی'),
        ),
    ]
