# Generated by Django 5.0.14 on 2026-09-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('employees', '0010_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حضور'), ('absent', 'غیبت'), ('leave', 'مرخصی'), ('mission', 'مأموریت'), ('holiday', 'تعطیل')], default='present', max_length=20, verbose_name='وضعیت')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='ورود')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='خروج')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعت کاری')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='اضافهکار')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'رکورد حضور',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ['-date', 'employee__employee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'date'), name='uniq_attendance_employee_date'),
        ),
    ]
