# Generated by Django 5.0.14 on 2026-08-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(max_length=50, verbose_name='شماره ابلاغ')),
                ('date', models.DateField(verbose_name='تاریخ ابلاغ')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('appointment', 'انتصاب'), ('promotion', 'ارتقا'), ('warning', 'تذکر'), ('appreciation', 'تقدیر'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='نوع ابلاغ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employees', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='گیرندگان ابلاغ')),
            ],
            options={
                'verbose_name': 'ابلاغ',
                'verbose_name_plural': 'ابلاغ\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام فرم')),
                ('code', models.CharField(max_length=50, verbose_name='کد فرم')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='correspondences/forms/', verbose_name='فایل فرم')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'فرم',
                'verbose_name_plural': 'فرم\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(max_length=50, verbose_name='شماره نامه')),
                ('date', models.DateField(verbose_name='تاریخ نامه')),
                ('sender', models.CharField(max_length=200, verbose_name='فرستنده')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='correspondences/incoming/', verbose_name='فایل پیوست')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='پرسنل مرتبط')),
            ],
            options={
                'verbose_name': 'نامه وارده',
                'verbose_name_plural': 'نامه\u200cهای وارده',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(max_length=50, verbose_name='شماره نامه')),
                ('date', models.DateField(verbose_name='تاریخ نامه')),
                ('receiver', models.CharField(max_length=200, verbose_name='گیرنده')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='correspondences/outgoing/', verbose_name='فایل پیوست')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='پرسنل مرتبط')),
            ],
            options={
                'verbose_name': 'نامه صادره',
                'verbose_name_plural': 'نامه\u200cهای صادره',
                'ordering': ['-date'],
            },
        ),
    ]
