# Generated by Django 5.0.14 on 2026-08-17 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('correspondences', '0001_initial'),
        ('employees', '0004_contracttype_alter_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='correspondences/announcements/', verbose_name='فایل پیوست'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام سازمان')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('type', models.CharField(choices=[('tax', 'اداره مالیات'), ('social_security', 'تأمین اجتماعی'), ('insurance', 'بیمه'), ('court', 'دادگستری / مراجع قضایی'), ('bank', 'بانک'), ('government', 'سازمان دولتی'), ('other', 'سایر')], default='government', max_length=50, verbose_name='نوع سازمان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(max_length=50, verbose_name='شماره نامه')),
                ('date', models.DateField(verbose_name='تاریخ نامه')),
                ('letter_type', models.CharField(choices=[('notice', 'اطلاع رسانی'), ('edict', 'ابلاغ'), ('seizure', 'بازداشت نامه'), ('summons', 'احضاریه'), ('warning', 'هشدار / تذکر'), ('request', 'درخواست'), ('response', 'پاسخ'), ('other', 'سایر')], default='notice', max_length=30, verbose_name='نوع مکاتبه')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='correspondences/organizational/', verbose_name='فایل پیوست')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='پرسنل مرتبط')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='correspondences.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'مکاتبه سازمانی',
                'verbose_name_plural': 'مکاتبات سازمانی',
                'ordering': ['-date'],
            },
        ),
    ]
