# Generated by Django 5.0.14 on 2026-09-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('correspondences', '0002_announcement_file_organization_organizationalletter'),
        ('employees', '0011_add_hr_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingletter',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='outgoingletter',
            name='employee',
        ),
        migrations.AddField(
            model_name='incomingletter',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='incoming_letters', to='employees.employee', verbose_name='پرسنل مرتبط'),
        ),
        migrations.AddField(
            model_name='outgoingletter',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='outgoing_letters', to='employees.employee', verbose_name='پرسنل مرتبط'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='form',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='organizationalletter',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='company',
            field=models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت'),
        ),
    ]
