# Generated by Django 5.0.14 on 2026-09-28 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0018_alter_accountingdocument_source_id_and_more'),
        ('core', '0011_enable_procurement_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=30, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('entity_type', models.CharField(choices=[('bank', 'بانک'), ('cash', 'صندوق')], default='bank', max_length=10, verbose_name='نوع نهاد')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('sheba_number', models.CharField(blank=True, max_length=30, verbose_name='شماره شبا')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ماندهٔ ابتدایی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='حساب معین مرتبط')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'نهاد پولی خزانه',
                'verbose_name_plural': 'نهادهای پولی خزانه',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('source_type', models.CharField(choices=[('purchase_invoice', 'صورتحساب خرید'), ('salary', 'حقوق'), ('contract_invoice', 'فاکتور قرارداد'), ('project_statement', 'صورت\u200cوضعیت پروژه')], max_length=30, verbose_name='نوع مبدأ')),
                ('source_id', models.CharField(max_length=64, verbose_name='شناسهٔ مبدأ')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('party', models.CharField(blank=True, max_length=250, verbose_name='طرف حساب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='پرداخت\u200cشده')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تسویه شده')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'آیتم قابل پرداخت',
                'verbose_name_plural': 'آیتم\u200cهای قابل پرداخت',
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'is_paid'], name='treasury_pa_company_bdae06_idx'), models.Index(fields=['company', 'due_date'], name='treasury_pa_company_415e7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره تراکنش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('direction', models.CharField(choices=[('receipt', 'دریافت'), ('payment', 'پرداخت')], max_length=10, verbose_name='جهت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('party', models.CharField(blank=True, max_length=250, verbose_name='طرف حساب')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('source_module', models.CharField(blank=True, max_length=50, verbose_name='ماژول مبدأ')),
                ('source_id', models.CharField(blank=True, max_length=64, verbose_name='شناسهٔ مبدأ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت شده'), ('cancelled', 'لغو')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.treasuryentity', verbose_name='بانک/صندوق')),
            ],
            options={
                'verbose_name': 'تراکنش خزانه',
                'verbose_name_plural': 'تراکنش\u200cهای خزانه',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'entity'], name='treasury_tr_company_34df36_idx'), models.Index(fields=['company', 'direction'], name='treasury_tr_company_971e7e_idx')],
            },
        ),
    ]
