# Generated by Django 5.0.14 on 2026-09-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_enable_treasury_module'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد دسته\u200cچک')),
                ('bank_name', models.CharField(max_length=200, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('series_start', models.CharField(blank=True, max_length=50, verbose_name='شروع سری')),
                ('series_end', models.CharField(blank=True, max_length=50, verbose_name='پایان سری')),
                ('total_leaves', models.PositiveIntegerField(default=0, verbose_name='تعداد برگ')),
                ('used_leaves', models.PositiveIntegerField(default=0, verbose_name='برگ مصرف\u200cشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkbooks', to='treasury.treasuryentity', verbose_name='نهاد مرتبط')),
            ],
            options={
                'verbose_name': 'دسته\u200cچک',
                'verbose_name_plural': 'دسته\u200cچک\u200cها',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IssuedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('party', models.CharField(max_length=250, verbose_name='ذینفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادرشده'), ('cleared', 'پاس\u200cشده'), ('bounced', 'برگشتی'), ('cancelled', 'لغو')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('checkbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='treasury.checkbook', verbose_name='دسته\u200cچک')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'چک پرداختی',
                'verbose_name_plural': 'چک\u200cهای پرداختی',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='treasury_is_company_66e427_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceivedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('bank_name', models.CharField(max_length=200, verbose_name='بانک صادرکننده')),
                ('party', models.CharField(max_length=250, verbose_name='طرف حساب (صادرکننده)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('registered', 'ثبت\u200cشده'), ('deposited', 'واریز به حساب'), ('cleared', 'پاس\u200cشده'), ('bounced', 'برگشتی'), ('endorsed', 'ظهرنویسی\u200cشده'), ('cancelled', 'لغو')], default='registered', max_length=15, verbose_name='وضعیت')),
                ('endorsed_to', models.CharField(blank=True, max_length=250, verbose_name='ظهرنویسی به')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'چک دریافتی',
                'verbose_name_plural': 'چک\u200cهای دریافتی',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='treasury_re_company_3930d2_idx')],
            },
        ),
    ]
