# Generated by Django 5.0.14 on 2026-09-28 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_statement_currency'),
        ('core', '0012_enable_treasury_module'),
        ('procurement', '0001_initial'),
        ('projects', '0003_budgetline_committedcost_costtransaction_and_more'),
        ('treasury', '0002_checkbook_issuedcheck_receivedcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره تعهد')),
                ('source_type', models.CharField(blank=True, max_length=30, verbose_name='نوع مبدأ')),
                ('source_id', models.CharField(blank=True, max_length=64, verbose_name='شناسهٔ مبدأ')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان تعهد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ تعهد')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='پرداخت\u200cشده')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='سررسید')),
                ('status', models.CharField(choices=[('open', 'باز'), ('scheduled', 'برنامه\u200cریزی\u200cشده'), ('partial', 'پرداخت جزئی'), ('paid', 'تسویه\u200cشده'), ('cancelled', 'لغو')], default='open', max_length=15, verbose_name='وضعیت')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_commitments', to='contracts.contract', verbose_name='قرارداد')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_commitments', to='contracts.contractparty', verbose_name='طرف حساب')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_commitments', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تعهد نقدی',
                'verbose_name_plural': 'تعهدات نقدی',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره درخواست')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان درخواست')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='واحد درخواست')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ درخواستی')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='مبلغ تأییدشده')),
                ('requested_date', models.DateField(verbose_name='تاریخ درخواست')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('source_type', models.CharField(blank=True, max_length=30, verbose_name='نوع مبدأ')),
                ('source_id', models.CharField(blank=True, max_length=64, verbose_name='شناسهٔ مبدأ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('under_review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('scheduled', 'برنامه\u200cریزی\u200cشده'), ('payment_ordered', 'دستور پرداخت صادرشده'), ('paid', 'پرداخت\u200cشده'), ('rejected', 'رد شده'), ('returned', 'برگشت\u200cخورده'), ('cancelled', 'لغو')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='treasury.paymentcommitment', verbose_name='تعهد مرتبط')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_payment_requests', to='contracts.contract', verbose_name='قرارداد')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_payment_requests', to='contracts.contractparty', verbose_name='طرف حساب')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_payment_requests', to='projects.project', verbose_name='پروژه')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_payment_requests', to='procurement.supplier', verbose_name='تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست پرداخت',
                'verbose_name_plural': 'درخواست\u200cهای پرداخت',
                'ordering': ['-requested_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره دستور')),
                ('instrument', models.CharField(choices=[('transfer', 'انتقال بانکی'), ('cheque', 'چک'), ('cash', 'نقد'), ('card', 'کارت')], default='transfer', max_length=15, verbose_name='ابزار پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اجرا')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادرشده'), ('executed', 'اجراشده'), ('returned', 'برگشتی'), ('cancelled', 'لغو')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='treasury.treasuryentity', verbose_name='بانک/صندوق')),
                ('issued_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='treasury.issuedcheck', verbose_name='چک صادرشده')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='treasury.paymentrequest', verbose_name='درخواست پرداخت')),
            ],
            options={
                'verbose_name': 'دستور پرداخت',
                'verbose_name_plural': 'دستورهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=30, verbose_name='کد')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('target', models.CharField(choices=[('bank', 'بانک'), ('cash', 'صندوق'), ('cheque', 'چک'), ('card', 'کارت')], default='bank', max_length=10, verbose_name='مقصد ابزار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='treasury.treasurypaymentmethod', verbose_name='روش پرداخت'),
        ),
        migrations.CreateModel(
            name='TreasuryPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('code', models.CharField(max_length=30, verbose_name='کد')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('requires_contract', models.BooleanField(default=False, verbose_name='نیازمند قرارداد')),
                ('requires_project', models.BooleanField(default=False, verbose_name='نیازمند پروژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'نوع پرداخت',
                'verbose_name_plural': 'انواع پرداخت',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='treasury.treasurypaymenttype', verbose_name='نوع پرداخت'),
        ),
        migrations.AddIndex(
            model_name='paymentcommitment',
            index=models.Index(fields=['company', 'status'], name='treasury_pa_company_f4cb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcommitment',
            index=models.Index(fields=['company', 'due_date'], name='treasury_pa_company_f871c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='treasurypaymentmethod',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='treasurypaymenttype',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['company', 'status'], name='treasury_pa_company_b8a0de_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['company', 'due_date'], name='treasury_pa_company_18f5be_idx'),
        ),
    ]
