# Generated by Django 5.0.14 on 2026-09-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_statement_currency'),
        ('core', '0012_enable_treasury_module'),
        ('procurement', '0001_initial'),
        ('projects', '0003_budgetline_committedcost_costtransaction_and_more'),
        ('treasury', '0003_paymentcommitment_paymentrequest_paymentorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره علی\u200cالحساب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ علی\u200cالحساب')),
                ('date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('reason', models.TextField(blank=True, verbose_name='علت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('partial', 'تسویه جزئی'), ('settled', 'تسویه\u200cشده'), ('cancelled', 'لغو')], default='open', max_length=12, verbose_name='وضعیت')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_advances', to='contracts.contract', verbose_name='قرارداد')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_advances', to='contracts.contractparty', verbose_name='طرف حساب')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_advances', to='projects.project', verbose_name='پروژه')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_advances', to='procurement.supplier', verbose_name='تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'علی\u200cالحساب',
                'verbose_name_plural': 'علی\u200cالحساب\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ تسویه')),
                ('date', models.DateField(verbose_name='تاریخ تسویه')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='treasury.advanceaccount', verbose_name='علی\u200cالحساب')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'تسویه علی\u200cالحساب',
                'verbose_name_plural': 'تسویه\u200cهای علی\u200cالحساب',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره دریافت')),
                ('method', models.CharField(choices=[('bank', 'بانکی'), ('cash', 'نقدی'), ('cheque', 'چک')], default='bank', max_length=10, verbose_name='روش دریافت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مورد انتظار')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('status', models.CharField(choices=[('expected', 'مورد انتظار'), ('received', 'دریافت\u200cشده'), ('cleared', 'وصول\u200cشده'), ('returned', 'برگشت'), ('cancelled', 'لغو')], default='expected', max_length=12, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='treasury.treasuryentity', verbose_name='بانک/صندوق')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_receipts', to='contracts.contractparty', verbose_name='طرف حساب')),
                ('received_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='treasury.receivedcheck', verbose_name='چک دریافتی')),
            ],
            options={
                'verbose_name': 'دریافت',
                'verbose_name_plural': 'دریافت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره')),
                ('kind', models.CharField(choices=[('good_performance', 'حسن انجام کار'), ('tender', 'شرکت در مناقصه'), ('insurance', 'سپرده بیمه'), ('tax', 'سپرده مالیاتی'), ('guarantee_received', 'ضمانت\u200cنامه دریافتی'), ('guarantee_issued', 'ضمانت\u200cنامه صادرشده')], max_length=25, verbose_name='نوع')),
                ('issuer', models.CharField(blank=True, max_length=250, verbose_name='صادرکننده')),
                ('beneficiary', models.CharField(blank=True, max_length=250, verbose_name='ذی\u200cنفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آزادسازی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی\u200cشده'), ('released', 'آزادشده'), ('cancelled', 'لغو')], default='active', max_length=12, verbose_name='وضعیت')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_guarantees', to='contracts.contract', verbose_name='قرارداد')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_guarantees', to='contracts.contractparty', verbose_name='طرف حساب')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_guarantees', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'سپرده / ضمانت\u200cنامه',
                'verbose_name_plural': 'سپرده\u200cها و ضمانت\u200cنامه\u200cها',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='شماره انتقال')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('date', models.DateField(verbose_name='تاریخ انتقال')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت\u200cشده'), ('cancelled', 'لغو')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='تاریخچهٔ چرخه')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='treasury.treasuryentity', verbose_name='مقصد')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='treasury.treasuryentity', verbose_name='مبدأ')),
            ],
            options={
                'verbose_name': 'انتقال وجه',
                'verbose_name_plural': 'انتقال\u200cهای وجه',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advanceaccount',
            index=models.Index(fields=['company', 'status'], name='treasury_ad_company_135df7_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['company', 'status'], name='treasury_re_company_9a6aad_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryguarantee',
            index=models.Index(fields=['company', 'status'], name='treasury_tr_company_afe63d_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryguarantee',
            index=models.Index(fields=['company', 'expiry_date'], name='treasury_tr_company_22cc74_idx'),
        ),
    ]
