# Generated by Django 5.0.14 on 2026-09-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_enable_treasury_module'),
        ('treasury', '0004_advanceaccount_advancesettlement_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('as_of', models.DateField(verbose_name='تاریخ مغایرت\u200cگیری')),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='موجودی اعلامی')),
                ('book_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='مانده دفتری')),
                ('difference', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='اختلاف')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت\u200cشده'), ('cancelled', 'لغو')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='treasury.treasuryentity', verbose_name='بانک/صندوق')),
            ],
            options={
                'verbose_name': 'مغایرت خزانه',
                'verbose_name_plural': 'مغایرت\u200cهای خزانه',
                'ordering': ['-as_of', '-created_at'],
            },
        ),
    ]
