# Generated by Django 5.0.14 on 2026-10-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره اموال'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'لپ\u200cتاپ'), ('computer', 'سیستم رایانه\u200cای'), ('phone', 'موبایل'), ('telephone', 'تلفن ثابت'), ('desk', 'میز کار'), ('chair', 'صندلی'), ('monitor', 'مانیتور'), ('scanner', 'اسکنر'), ('printer', 'پرینتر'), ('money_counter', 'پول\u200cشمار'), ('office_supplies', 'لوازم اداری'), ('cabinet', 'کمد'), ('wooden_files', 'فایل\u200cهای چوبی'), ('key', 'کلید'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع دارایی'),
        ),
    ]
