# Generated by Django 5.0.14 on 2026-10-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0020_alter_accountingdocument_approved_by_and_more'),
        ('core', '0013_rolepermission_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام برنامه مبدا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'منبع داده',
                'verbose_name_plural': 'منابع داده',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MappingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('level', models.CharField(choices=[('group', 'گروه حساب'), ('general', 'حساب کل'), ('subsidiary', 'حساب معین'), ('auxiliary', 'حساب تفصیلی')], max_length=20, verbose_name='سطح کدینگ')),
                ('source_code', models.CharField(blank=True, max_length=50, verbose_name='کد مبدا')),
                ('source_name', models.CharField(blank=True, max_length=250, verbose_name='عنوان مبدا')),
                ('match_score', models.FloatField(default=0, verbose_name='امتیاز شباهت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('matched', 'نگاشت\u200cشده'), ('new', 'ایجاد جدید'), ('ignored', 'نادیده گرفته')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('resolved', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='حساب هدف')),
                ('target_auxiliary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.auxiliaryaccount', verbose_name='تفصیلی هدف')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.accountgroup', verbose_name='گروه هدف')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='datamapping.mappingsource', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'نگاشت کد',
                'verbose_name_plural': 'نگاشت کدها',
                'ordering': ['level', 'source_code'],
                'unique_together': {('company', 'source', 'level', 'source_code')},
            },
        ),
    ]
