# Generated by Django 5.0.14 on 2026-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingentry',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='دسته تفصیلی'),
        ),
    ]
