# Generated by Django 5.0.14 on 2026-09-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rolepermission_remove_company_created_on_and_more'),
        ('employees', '0010_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('leave_type', models.CharField(choices=[('annual', 'مرخصی استحقاقی'), ('sick', 'مرخصی استعلاجی'), ('mission', 'مأموریت'), ('unpaid', 'مرخصی بدون حقوق'), ('marriage', 'مرخصی ازدواج'), ('maternity', 'مرخصی زایمان'), ('other', 'سایر')], default='annual', max_length=30, verbose_name='نوع مرخصی/مأموریت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('days', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='تعداد روز')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل/توضیح')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='employees.employee', verbose_name='تأییدکننده')),
                ('company', models.ForeignKey(db_constraint=False, help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'درخواست مرخصی/مأموریت',
                'verbose_name_plural': 'مرخصی و مأموریت',
                'ordering': ['-created_at'],
            },
        ),
    ]
