# Generated by Django 5.0.14 on 2026-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='ساعت (برای مرخصی ساعتی)'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'مرخصی استحقاقی'), ('sick', 'مرخصی استعلاجی'), ('mission', 'مأموریت'), ('hourly', 'مرخصی ساعتی'), ('unpaid', 'مرخصی بدون حقوق'), ('marriage', 'مرخصی ازدواج'), ('maternity', 'مرخصی زایمان'), ('other', 'سایر')], default='annual', max_length=30, verbose_name='نوع مرخصی/مأموریت'),
        ),
    ]
