# Generated by Django 5.0.14 on 2026-08-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل حقوقی')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره ثبت')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد اقتصادی')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='لوگو')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه مالیاتی')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'مشخصات شرکت',
                'verbose_name_plural': 'مشخصات شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن رکورد', verbose_name='فعال')),
                ('key', models.CharField(max_length=100, verbose_name='کلید تنظیم')),
                ('value', models.TextField(help_text='مقدار تنظیم (همیشه به\u200cصورت متن ذخیره می\u200cشود)', verbose_name='مقدار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('data_type', models.CharField(choices=[('string', 'متن'), ('integer', 'عدد صحیح'), ('boolean', 'بله/خیر'), ('json', 'JSON'), ('file_path', 'مسیر فایل')], default='string', max_length=20, verbose_name='نوع داده')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل ویرایش')),
                ('company', models.ForeignKey(help_text='شرکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'تنظیم سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'ordering': ['key'],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
