# Generated by Django 5.0.14 on 2026-09-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_balecontact_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balecontact',
            name='tag',
            field=models.CharField(blank=True, help_text='مثلاً: مشتری، هیئت‌مدیره، قرارداد', max_length=100, null=True, verbose_name='برچسب'),
        ),
    ]