# Generated by Django 5.0.14 on 2026-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_merge_0007_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='storage_path_correspondences',
            field=models.CharField(blank=True, help_text='پوشهٔ لازم برای نامه\u200cها و مکاتبات', max_length=500, verbose_name='مسیر مکاتبات'),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
